In [1]:
import pandas as pd
import numpy as np
import os 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, recall_score, accuracy_score, classification_report, precision_score
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

In [2]:
#Chargement du DF
data = pd.read_excel('Copie de Coeur.xlsx')

In [3]:
#Travailler avec une copie du data Frame pour éviter de le rechager en cas d'êrreur
df = data.copy()

In [4]:
#Afficher les informations relatives au DF
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   AGE          918 non-null    int64  
 1   SEXE         918 non-null    object 
 2   TDT          918 non-null    object 
 3   PAR          918 non-null    int64  
 4   CHOLESTEROL  918 non-null    int64  
 5   GAJ          918 non-null    int64  
 6   ECG          918 non-null    object 
 7   FCMAX        918 non-null    int64  
 8   ANGINE       918 non-null    object 
 9   DEPRESSION   918 non-null    float64
 10  PENTE        918 non-null    object 
 11  CŒUR         918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [5]:
#Normalisation des variables quantitatives
for col in df.drop('CŒUR', axis =1).select_dtypes(np.number).columns:
    df[col] = df[col]/df[col].max()


In [6]:
#Vérification des résultats
df.head()

AGE   SEXE  TDT   PAR  CHOLESTEROL  GAJ     ECG     FCMAX ANGINE  \
0  0.519481  homme   AA  0.70     0.479270  0.0  Normal  0.851485    Non   
1  0.636364  femme  DNA  0.80     0.298507  0.0  Normal  0.772277    Non   
2  0.480519  homme   AA  0.65     0.469320  0.0      ST  0.485149    Non   
3  0.623377  femme  ASY  0.69     0.354892  0.0  Normal  0.534653    Oui   
4  0.701299  homme  DNA  0.75     0.323383  0.0  Normal  0.603960    Non   

   DEPRESSION       PENTE  CŒUR  
0     0.000000  Ascendant     0  
1     0.161290       Plat     1  
2     0.000000  Ascendant     0  
3     0.241935       Plat     1  
4     0.000000  Ascendant     0

In [7]:
#Encodage des variables qualitatives
for col in df.select_dtypes('object').columns:
    df[col] = df[col].astype('category').cat.codes

In [8]:
#Vérification des résultats
df.head()

AGE  SEXE  TDT   PAR  CHOLESTEROL  GAJ  ECG     FCMAX  ANGINE  \
0  0.519481     1    0  0.70     0.479270  0.0    1  0.851485       0   
1  0.636364     0    3  0.80     0.298507  0.0    1  0.772277       0   
2  0.480519     1    0  0.65     0.469320  0.0    2  0.485149       0   
3  0.623377     0    1  0.69     0.354892  0.0    1  0.534653       1   
4  0.701299     1    3  0.75     0.323383  0.0    1  0.603960       0   

   DEPRESSION   PENTE  CŒUR  
0     0.000000      0     0  
1     0.161290      2     1  
2     0.000000      0     0  
3     0.241935      2     1  
4     0.000000      0     0

In [9]:
#Séparer la variable cible (coeur) et les variables explicatives
y = df['CŒUR']
x = df.drop('CŒUR', axis = 1)

In [10]:
#Subdivision du jeu de données en apprentissage et en test
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size =0.2, random_state =1)
#train_set, test_set = train_test_split(df,test_size =0.2, random_state =1)

In [11]:
#Vérifier le résultat
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(734, 11) (184, 11) (734,) (184,)


In [12]:
#Création d'un objet lr de la classe LogisticRegression
lr = LogisticRegression(solver ='newton-cg', random_state =1)

In [13]:
#Apprentissage du modèle
model = lr.fit(x_train, y_train)
#model = lr.fit(train_set.drop('CŒUR', axis = 1), train_set['CŒUR'])

In [14]:
#Probabilité d'appartenance à l'une des classes
predict_proba = model.predict_proba(x_test)
predict_proba[:5,:]

array([[0.39560595, 0.60439405],
       [0.18843348, 0.81156652],
       [0.04970935, 0.95029065],
       [0.09007617, 0.90992383],
       [0.28158313, 0.71841687]])

In [15]:
#Application du modèle au données de test
y_pred = model.predict(x_test)
y_pred[:5]

array([1, 1, 1, 1, 1], dtype=int64)

In [16]:
#matrice de confusion
mc = confusion_matrix(y_test, y_pred)
mc

array([[ 66,   8],
       [  6, 104]], dtype=int64)

In [17]:
#Taux de bonnes prédictions
accuracy = accuracy_score(y_test, y_pred)
accuracy
#Conclusion : le modèle produit 85.32 % de bonne prédiction.

0.9239130434782609

In [18]:
#Sensibilité
recall = recall_score(y_test, y_pred)
recall
#conclusion : lorsqu'un individu est malade, nous avons 84.11 % de chance que le modèle le prédise.

0.9454545454545454

In [19]:
#Précision
precision = precision_score(y_test, y_pred)
precision
#Conclusion : lorsque le modèle prédit qu'un individu est malade, nous avons 90 % de chace que cela soit vraie.

0.9285714285714286

In [20]:
#plus de détails avec classification report
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.92      0.89      0.90        74
           1       0.93      0.95      0.94       110

    accuracy                           0.92       184
   macro avg       0.92      0.92      0.92       184
weighted avg       0.92      0.92      0.92       184



In [21]:
#Modèle Trival
df['CŒUR'].value_counts()/df.shape[0]
#Conclusion : si nous nous basons sur le hasard pour faire nos prédiction, nous aurons 55.37 % de bonne prédiction.

1    0.553377
0    0.446623
Name: CŒUR, dtype: float64

In [22]:
#Score d'entrainement (le taux de bonne prédiction calculé sur la base des données d'entrainement)
model.score(x_train, y_train)

0.8433242506811989

In [23]:
#Score d'entrainement (le taux de bonne prédiction calculé sur la base des données de test)
model.score(x_test, y_test)

0.9239130434782609

In [24]:
df

AGE  SEXE  TDT   PAR  CHOLESTEROL  GAJ  ECG     FCMAX  ANGINE  \
0    0.519481     1    0  0.70     0.479270  0.0    1  0.851485       0   
1    0.636364     0    3  0.80     0.298507  0.0    1  0.772277       0   
2    0.480519     1    0  0.65     0.469320  0.0    2  0.485149       0   
3    0.623377     0    1  0.69     0.354892  0.0    1  0.534653       1   
4    0.701299     1    3  0.75     0.323383  0.0    1  0.603960       0   
..        ...   ...  ...   ...          ...  ...  ...       ...     ...   
913  0.584416     1    2  0.55     0.437811  0.0    1  0.653465       0   
914  0.883117     1    1  0.72     0.320066  1.0    1  0.698020       0   
915  0.740260     1    1  0.65     0.217247  0.0    1  0.569307       1   
916  0.740260     0    0  0.65     0.391376  0.0    0  0.861386       0   
917  0.493506     1    3  0.69     0.290216  0.0    1  0.856436       0   

     DEPRESSION   PENTE  CŒUR  
0       0.000000      0     0  
1       0.161290      2     1  
2       0.000000      0     0  
3       0.241935      2     1  
4       0.000000      0     0  
..           ...    ...   ...  
913     0.193548      2     1  
914     0.548387      2     1  
915     0.193548      2     1  
916     0.000000      2     1  
917     0.000000      0     0  

[918 rows x 12 columns]

# DecisionTree

In [25]:
data

AGE   SEXE  TDT  PAR  CHOLESTEROL  GAJ     ECG  FCMAX ANGINE  \
0     40  homme   AA  140          289    0  Normal    172    Non   
1     49  femme  DNA  160          180    0  Normal    156    Non   
2     37  homme   AA  130          283    0      ST     98    Non   
3     48  femme  ASY  138          214    0  Normal    108    Oui   
4     54  homme  DNA  150          195    0  Normal    122    Non   
..   ...    ...  ...  ...          ...  ...     ...    ...    ...   
913   45  homme   AT  110          264    0  Normal    132    Non   
914   68  homme  ASY  144          193    1  Normal    141    Non   
915   57  homme  ASY  130          131    0  Normal    115    Oui   
916   57  femme   AA  130          236    0     LVH    174    Non   
917   38  homme  DNA  138          175    0  Normal    173    Non   

     DEPRESSION       PENTE  CŒUR  
0            0.0  Ascendant     0  
1            1.0       Plat     1  
2            0.0  Ascendant     0  
3            1.5       Plat     1  
4            0.0  Ascendant     0  
..           ...        ...   ...  
913          1.2       Plat     1  
914          3.4       Plat     1  
915          1.2       Plat     1  
916          0.0       Plat     1  
917          0.0  Ascendant     0  

[918 rows x 12 columns]

In [26]:
#faire une copie du dataFrame de base pour avoir un autre sur lequel je pourais appliquer mon arbre de décision 

In [27]:
df_AD = data.copy()

In [28]:
df_AD

AGE   SEXE  TDT  PAR  CHOLESTEROL  GAJ     ECG  FCMAX ANGINE  \
0     40  homme   AA  140          289    0  Normal    172    Non   
1     49  femme  DNA  160          180    0  Normal    156    Non   
2     37  homme   AA  130          283    0      ST     98    Non   
3     48  femme  ASY  138          214    0  Normal    108    Oui   
4     54  homme  DNA  150          195    0  Normal    122    Non   
..   ...    ...  ...  ...          ...  ...     ...    ...    ...   
913   45  homme   AT  110          264    0  Normal    132    Non   
914   68  homme  ASY  144          193    1  Normal    141    Non   
915   57  homme  ASY  130          131    0  Normal    115    Oui   
916   57  femme   AA  130          236    0     LVH    174    Non   
917   38  homme  DNA  138          175    0  Normal    173    Non   

     DEPRESSION       PENTE  CŒUR  
0            0.0  Ascendant     0  
1            1.0       Plat     1  
2            0.0  Ascendant     0  
3            1.5       Plat     1  
4            0.0  Ascendant     0  
..           ...        ...   ...  
913          1.2       Plat     1  
914          3.4       Plat     1  
915          1.2       Plat     1  
916          0.0       Plat     1  
917          0.0  Ascendant     0  

[918 rows x 12 columns]

In [29]:
#Normalisation des variables quantitatives
for col in df_AD.drop('CŒUR', axis =1).select_dtypes(np.number).columns:
    df_AD[col] = df_AD[col]/df_AD[col].max()


In [30]:
#Vérification des résultats
df_AD.head()

AGE   SEXE  TDT   PAR  CHOLESTEROL  GAJ     ECG     FCMAX ANGINE  \
0  0.519481  homme   AA  0.70     0.479270  0.0  Normal  0.851485    Non   
1  0.636364  femme  DNA  0.80     0.298507  0.0  Normal  0.772277    Non   
2  0.480519  homme   AA  0.65     0.469320  0.0      ST  0.485149    Non   
3  0.623377  femme  ASY  0.69     0.354892  0.0  Normal  0.534653    Oui   
4  0.701299  homme  DNA  0.75     0.323383  0.0  Normal  0.603960    Non   

   DEPRESSION       PENTE  CŒUR  
0     0.000000  Ascendant     0  
1     0.161290       Plat     1  
2     0.000000  Ascendant     0  
3     0.241935       Plat     1  
4     0.000000  Ascendant     0

In [31]:
#Encodage des variables qualitatives dans une variable le

le = LabelEncoder()

In [32]:
#creer une variable df_encoded qui va stocker notre dataframe encoder
df_encoded=df.iloc[:,0:12]

In [33]:
#recodons par exemple le 'PENTE'
le.fit_transform(df_encoded["PENTE"])



array([0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2,
       0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0,
       2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 2, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0,
       0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2,
       2, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 2, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2,
       2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 2, 2, 0, 2, 0, 2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2,
       2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0,
       2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 0,
       2, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2,
       2, 0, 2, 0, 2, 1, 2, 2, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2,
       2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2,

In [34]:
#Dans une fonction application cette modification à tout notre DataFrame
for i in df_encoded:
    df_encoded[i]=le.fit_transform(df_encoded[i])


In [35]:
df_encoded.head()

AGE  SEXE  TDT  PAR  CHOLESTEROL  GAJ  ECG  FCMAX  ANGINE  DEPRESSION   \
0   12     1    0   41          147    0    1     98       0           10   
1   21     0    3   55           40    0    1     82       0           20   
2    9     1    0   31          141    0    2     25       0           10   
3   20     0    1   39           72    0    1     34       1           25   
4   26     1    3   49           53    0    1     48       0           10   

   PENTE  CŒUR  
0      0     0  
1      2     1  
2      0     0  
3      2     1  
4      0     0

In [36]:
# jeu de fonctionnalités
x=df_encoded.iloc[:,0:11]
#jeu d'étiquettes
y=df_encoded.iloc[:,11]

In [37]:
#Subdivision du jeu de données en apprentissage et en test
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size =0.2, random_state =1)
#train_set, test_set = train_test_split(df,test_size =0.2, random_state =1)

In [38]:
#Vérifier le résultat
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(734, 11) (184, 11) (734,) (184,)


In [39]:
#Création d'un objet model de la classe DecisionTreeClassifier
model_AD=DecisionTreeClassifier(criterion='gini')
#Gini est une formule mathematique de la fonction CART

In [40]:
#Apprentissage du modèle
model_AD.fit(x_train,y_train)

DecisionTreeClassifier()

In [41]:
#Probabilité d'appartenance à l'une des classes
predict_proba = model_AD.predict_proba(x_test)
predict_proba[:5,:]

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [42]:
#Application du modèle au données de test
y_pred = model_AD.predict(x_test)
y_pred[:5]

array([1, 0, 1, 1, 0], dtype=int64)

In [43]:
#matrice de confusion
mc = confusion_matrix(y_test, y_pred)
mc

array([[63, 11],
       [23, 87]], dtype=int64)

In [44]:
#Taux de bonnes prédictions
accuracy = accuracy_score(y_test, y_pred)
accuracy
#Conclusion : le modèle produit 81 % de bonne prédiction.

0.8152173913043478

In [45]:
#Sensibilité
recall_AD = recall_score(y_test, y_pred)
recall_AD
#conclusion : lorsqu'un individu est malade, nous avons 79 % de chance que le modèle le prédise.

0.7909090909090909

In [46]:
#Précision
precision_AD = precision_score(y_test, y_pred)
precision_AD
#Conclusion : lorsque le modèle prédit qu'un individu est malade, nous avons 87,9 % de chace que cela soit vraie.

0.8877551020408163

In [47]:
#plus de détails avec classification report
cr_AD = classification_report(y_test, y_pred)
print(cr_AD)

              precision    recall  f1-score   support

           0       0.73      0.85      0.79        74
           1       0.89      0.79      0.84       110

    accuracy                           0.82       184
   macro avg       0.81      0.82      0.81       184
weighted avg       0.83      0.82      0.82       184



In [48]:
#Score d'entrainement (le taux de bonne prédiction calculé sur la base des données d'entrainement)
model_AD.score(x_train, y_train)

1.0

In [49]:
#Score d'entrainement (le taux de bonne prédiction calculé sur la base des données de test)
model_AD.score(x_test, y_test)

0.8152173913043478

# Comparaison des scores entre la Régression Linéaire et L'Arbre de Décision

In [50]:
#Comparaison au niveau des  Score d'entrainement (le taux de bonne prédiction calculé sur la base des données d'entrainement)
if model.score(x_train, y_train) > model_AD.score(x_train, y_train):
    print("Sur l'entrainement, le resultat de la Régression Logistique est supérieure à celui de l'Arbre de Décision")
else:
    print("Sur l'entrainement, le resultat de la Régression Logistique est inférieure à celui de l'Arbre de Décision")

Sur l'entrainement, le resultat de la Régression Logistique est inférieure à celui de l'Arbre de Décision


In [51]:
#Comparaison au niveau des Score d'entrainement (le taux de bonne prédiction calculé sur la base des données de test)
if model.score(x_test, y_test) > model_AD.score(x_test, y_test):
    print("Sur l'entrainement,le resultat de la Régression Logistique est supérieure à celui de l'Arbre de Décision")
else:
    print("Sur l'entrainement,le resultat de la Régression Logistique est inférieure à celui de l'Arbre de Décision")

Sur l'entrainement,le resultat de la Régression Logistique est inférieure à celui de l'Arbre de Décision


In [52]:
if model.score(x_train, y_train) < model_AD.score(x_train, y_train) and model.score(x_test, y_test) < model_AD.score(x_test, y_test):
    print("L'arbre de Décisin produit un bon résultat par raport à celle de la Régression Log")

L'arbre de Décisin produit un bon résultat par raport à celle de la Régression Log
